---
language: java
jdk:
  - openjdk11
  - openjdk8

install: skip
script:
  - cp -f .travis.settings.xml $HOME/.m2/settings.xml
  - ./mvnw -T2 clean package
after_success:
  - bash <(curl -s https://codecov.io/bash)
...