---
name: JDK15
on:
  push:         {branches: [ develop ]}
  pull_request: {branches: [ develop ]}

jobs:
  build:
    runs-on: ubuntu-latest
    env: {GITHUB_TOKEN: '${{ secrets.GH_TOKEN }}'}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: {java-version: 15}

    - run: java -version
    - run: cp -f .ci.settings.xml $HOME/.m2/settings.xml
    - run: ./mvnw -B -f octopussy-cdc/pom.xml install
    - run: ./mvnw -B install
...