---
name: JDK8
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: cp -f .ci.settings.xml $HOME/.m2/settings.xml
    - run: ./mvnw -B package org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report -DrepoToken=$COVERALLS_TOKEN
...